# Generated by Django 3.0.14 on 2022-02-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Module',
        ),
    ]
