# Generated by Django 3.0.14 on 2022-02-15 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['title'], 'permissions': [('change_task_status', 'Can change the status of tasks'), ('close_task', 'Can remove a task by setting its status as closed')]},
        ),
    ]
