# Generated by Django 3.0.14 on 2022-02-15 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20220215_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['title'], 'permissions': [('change_task_status', 'Может поменять'), ('close_task', 'Can remove a task by setting its status as closed')]},
        ),
    ]
